package clarence.key_expression;

public enum Funcs {
	
	MULT,DIV,ADD,SUB,REM,EXPONENTIAL,OR,AND,NOT,EQ,NE,GT,LT,GE,LE,ABS,ACOS,
	ASIN,ATAN,COS,EXP,FTOA,INT,LOG,LOG10,MAX,MIN,MOD,POW,SIN,SQRT,STRUPPER,STRLOWER,TAN,
	CALCAZ,CALCDEGN,DAYOFWEEK,ERROR,GLOBAL,LOCAL,LOCALSTATUS,LOCALSYM,LOCALREF,LOCALREFSTATUS,
	MIRRORPOLYGON,PARAMETER,PARENT,PARENT2,PARENT3,PARENTSTATUS,PARENT2STATUS,PARENT3STATUS,PARENTSYM,
	PARENT2SYM,PARENT3SYM,PARENTREF,PARENT2REF,PARENT3REF,PARENTREFSTATUS,
	PARENT2REFSTATUS,PARENT3REFSTATUS,REFINDEX,SYMINDEX,SYMVALUE,RESVALUE,
	PARENTPV,CALCW,POLYAREA,SIT,NC,UNMINUS,UNKNOWN;

}
